### ISSUE TITLE
RPC-call with json parameter

### ISSUE THREAD

**Issue by yoyoyousei** [tedeh/jayson#111]
I'm trying to use jayson to do RPC request.
I succeeded rpc call with jayson, but rpc call with params of object failed.

Is jayson not to be used for rpc call with parameter of object?

Given error message is: 
```
{ Error: params unparseable
    at IncomingMessage.<anonymous> (/Users/s-sumi/ripplejs/node_modules/jayson/lib/client/http.js:74:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 400 }
```

my code (call blockchain daemon rpc method):
```
const params = {
    account: "rGJx52axFJ4VhBqviwhzMFibC6dTwR94ww",
    strict: true,
    ledger_index: "current",
    queue: true
};

const jayson = require('jayson');
const client = jayson.client.http({
    host: 's.altnet.rippletest.net',
    port: 51234
});

client.request('account_info', [JSON.stringify(params)], (err, response)=>{
    if(err){
        console.log(err);
    }
    console.log(response);
});
```

rpc call with curl succeeds 
```
curl -X POST "http://s.altnet.rippletest.net:51234" -H 'Content-Type: application/json; charset=utf-8' -d '{
    "method": "account_info",
    "params": [
        {
            "account": "rG1QQv2nh2gr7RCZ1P8YYcBUKCCN633jCn",
            "strict": true,
            "ledger_index": "current",
            "queue": true
        }
    ]
}'
```

Any commnents or advices are appreciated

**Comment by tedeh** [comment]
Don't JSON.stringify params.

**Comment by yoyoyousei** [comment]
Oops, thank you. it worked perfectly!
