### ISSUE TITLE
TypeError with collect: false and no params in request

### ISSUE THREAD

**Issue by mleonard87** [tedeh/jayson#71]
When using `collect: false` to not collect parameters into a single argument, if no parameters are supplied the error `TypeError: Cannot read property 'length' of undefined` is raised due to a length check on params which is null.

The JSON RPC 2.0 spec ([here](http://www.jsonrpc.org/specification#request_object)) says that `params` may be omitted.

```
/Users/mike/git/project/node_modules/jayson/lib/method.js:130
  if(handler.length !== (params.length + 1)) {
                               ^

TypeError: Cannot read property 'length' of undefined
    at Method.execute (/Users/mike/git/project/node_modules/jayson/lib/method.js:130:32)
    at /Users/mike/git/project/node_modules/jayson/lib/server/index.js:294:12
    at maybeParse (/Users/mike/git/project/node_modules/jayson/lib/server/index.js:411:5)
    at Server.call (/Users/mike/git/project/node_modules/jayson/lib/server/index.js:237:3)
    at /Users/mike/git/project/node_modules/jayson/lib/utils.js:189:14
    at /Users/mike/git/project/node_modules/jayson/node_modules/lodash/index.js:7173:25
    at /Users/mike/git/project/node_modules/jayson/lib/utils.js:162:7
    at Object.Utils.JSON.parse (/Users/mike/git/project/node_modules/jayson/lib/utils.js:284:3)
    at IncomingMessage.<anonymous> (/Users/mike/git/project/node_modules/jayson/lib/utils.js:160:16)
    at emitNone (events.js:80:13)
```

**Comment by tedeh** [comment]
Thank you
